# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitter_app', '0002_auto_20170523_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitt_text', models.CharField(max_length=140)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='avatars/avatar_default.jpeg', upload_to='avatars/%Y/%m/%d'),
        ),
    ]
