# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitter_app', '0003_auto_20170523_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='bitter_app.Profile'),
        ),
    ]
